create table person
(
    id            integer generated by default as identity
        primary key,
    full_name     varchar(50) not null
        unique,
    year_of_birth integer
        constraint person_year_of_birth_check
            check ((year_of_birth > 1900) AND
                   ((year_of_birth)::double precision < date_part('year'::text, CURRENT_DATE)))
);

alter table person
    owner to postgres;

create table book
(
    id              integer generated by default as identity
        primary key,
    name            varchar(50)  not null,
    author          varchar(150) not null,
    year_of_created integer
        constraint book_year_of_created_check
            check ((year_of_created)::double precision <= date_part('year'::text, CURRENT_DATE)),
    holder_id       integer
                                 references person
                                     on delete set null,
    receipt_date    timestamp,
    unique (name, author)
);

alter table book
    owner to postgres;

create table library_user
(
    id       integer generated by default as identity,
    username varchar not null
        unique,
    password varchar,
    role     varchar
);

alter table library_user
    owner to postgres;